# Generated by Django 3.2.9 on 2021-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passion', models.CharField(max_length=100)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkidin', models.URLField()),
                ('twitter', models.URLField()),
                ('skype', models.URLField()),
            ],
        ),
    ]
