# Generated by Django 3.2.9 on 2021-12-06 13:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=200)),
                ('Dob', models.DateField()),
                ('age', models.IntegerField(max_length=3)),
                ('website', models.URLField()),
                ('degree', models.CharField(choices=[('1', 'Higher Education'), ('2', 'Bachelor'), ('3', 'Diploma'), ('4', 'Master')], max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('Freelancer', models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=1)),
                ('about', models.TextField()),
                ('clients', models.IntegerField(max_length=10)),
                ('project', models.IntegerField(max_length=10)),
                ('Hrs', models.IntegerField(max_length=10)),
                ('Awards', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.user_profile')),
            ],
        ),
    ]
