# Generated by Django 3.2.9 on 2021-12-07 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_about',
            name='Awards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='Hrs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='clients',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='project',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, verbose_name='Seperate Skills With Comma : ')),
                ('skillpercentage', models.CharField(max_length=200, validators=[django.db.models.fields.CommaSeparatedIntegerField])),
                ('highereducationtitle', models.CharField(max_length=100)),
                ('highereducationYear', models.CharField(max_length=100)),
                ('highereducationName', models.CharField(max_length=100)),
                ('highereducationDescription', models.TextField()),
                ('primaryeducationtitle', models.CharField(max_length=100)),
                ('primaryeducationYear', models.CharField(max_length=100)),
                ('primaryeducationName', models.CharField(max_length=100)),
                ('primaryeducationDescription', models.TextField()),
                ('primaryWorktitle', models.CharField(max_length=100)),
                ('primaryWorkYear', models.CharField(max_length=100)),
                ('primaryWorkName', models.CharField(max_length=100)),
                ('primaryWorkDescription', models.TextField()),
                ('secondaryWorktitle', models.CharField(max_length=100)),
                ('secondaryWorkYear', models.CharField(max_length=100)),
                ('secondaryWorkName', models.CharField(max_length=100)),
                ('secondaryWorkDescription', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.user_profile')),
            ],
        ),
    ]
