# Generated by Django 3.2.9 on 2021-12-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20211208_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skill',
            field=models.CharField(max_length=200, verbose_name='Seperate Skills With Comma'),
        ),
        migrations.CreateModel(
            name='intrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('intrest', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.user_profile')),
            ],
        ),
    ]
