# Generated by Django 3.2.9 on 2021-12-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_auto_20211213_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=100, verbose_name='Name')),
                ('ClientProfile', models.CharField(max_length=100, verbose_name='Profile')),
                ('ClientWords', models.TextField()),
                ('ClientImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.user_profile')),
            ],
        ),
    ]
