# Generated by Django 3.2.9 on 2021-12-15 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
