# Generated by Django 3.2.9 on 2021-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_about',
            name='Dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='Freelancer',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_about',
            name='degree',
            field=models.CharField(choices=[('1', 'Higher Education'), ('2', 'Bachelor'), ('3', 'Diploma'), ('4', 'Master')], max_length=1, null=True),
        ),
    ]
