# Generated by Django 3.2.9 on 2021-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_alter_user_about_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='ClientImage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
