# Generated by Django 3.2.9 on 2021-12-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_auto_20211231_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(null=True, upload_to='newmedia'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='ClientImage',
            field=models.ImageField(null=True, upload_to='newmedia'),
        ),
    ]
