# Generated by Django 3.2.9 on 2022-01-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_auto_20211231_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
